/******************************************************************************
  Note : This is a Auto Generated File. DO NOT EDIT THIS FILE !!!
  FileName : ./apps/shell/cli/test_comm_mgr_lib_cli.h
  Date : 2020-05-21 11:35:26
*******************************************************************************/

#ifndef INCLUDE_SHELL_QUERY_H__
#define INCLUDE_SHELL_QUERY_H__


SHELL_APP_QUERY test_comm_mgr_lib_cli_query[] = 
{
	{
		 .token = 1,
		 .full_query = "show test_comm_mgr_lib_cli uptime",
	},
	{
		 .token = 2,
		 .full_query = "show test_comm_mgr_lib_cli option1",
	},
	{
		 .token = 3,
		 .full_query = "show test_comm_mgr_lib_cli option2",
	},
	{
		 .token = 0xFFFF,
	},
};



#endif /*INCLUDE_SHELL_QUERY_H__*/
