CC = gcc

# Pass gdb debug flag from command line
# Usage `make D=-g`
CC += $(D)

CFLAGS += -Wall -Wextra -Werror

C_SOURCES += $(wildcard *.c)
C_OBJECTS += $(C_SOURCES:.c=.o)

# Adding rpath, so that no need use the env variable LD_LIBRARY_PATH
LDFLAGS += \
	-L$(LIB_DIR) -Wl,-rpath=$(LIB_DIR)\

INCLUDE += \
