/*******************************************************************************
    Description : Communication manager common header files for server and lib

*******************************************************************************/
#ifndef INCLUDE_COMM_MGR_CMN_ENUMS_H__
#define INCLUDE_COMM_MGR_CMN_ENUMS_H__

#include "smarthome_essentials.h"

BEGIN_ENUM(COMM_MGR_CMN_ERR) {
    ADD_ENUM_VAL(COMM_MGR_CMN_SUCCESS, 0)
    ADD_ENUM(COMM_MGR_CMN_FAILURE)
    ADD_ENUM(COMM_MGR_CMN_PEER_DOWN)
    ADD_ENUM(COMM_MGR_CMN_INVALID_ARG)
    ADD_ENUM(COMM_MGR_CMN_BAD_COMM_MSG)
    ADD_ENUM(COMM_MGR_CMN_BAD_ANC_MSG)
    ADD_ENUM(COMM_MGR_CMN_NO_MEMORY)
} END_ENUM(COMM_MGR_CMN_ERR);

BEGIN_ENUM(COMM_MGR_PROTO_STATES) {
    ADD_ENUM(COMM_MGR_PROTO_DISCOVERY_START)
    ADD_ENUM(COMM_MGR_PROTO_DISCOVERY_DONE)
    ADD_ENUM(COMM_MGR_PROTO_LEARNING_START)
    ADD_ENUM(COMM_MGR_PROTO_LEARNING_DONE)
    ADD_ENUM(COMM_MGR_PROTO_DATATRANSFER_READY)
} END_ENUM(COMM_MGR_PROTO_STATES);

// Below are the main msg types
BEGIN_ENUM(COMM_MGR_MSG_TYPE) {
    ADD_ENUM_STR(COMM_MGR_MSG_PROTOCOL, "Used for discovery/learning")
    ADD_ENUM_STR(COMM_MGR_MSG_ACK, "Ack messages for protocol and data")
    ADD_ENUM_STR(COMM_MGR_MSG_DATA, "Used for data txfer after discovery")
    ADD_ENUM_STR(COMM_MGR_MSG_SYSTEM, "Used for sending system info")
    ADD_ENUM_STR(COMM_MGR_MSG_ANCILLARY, "Used for sending ancillary data")
    ADD_ENUM(COMM_MGR_MSG_MAX)
} END_ENUM(COMM_MGR_MSG_TYPE);

// Sub messages for each main msg types if required
BEGIN_ENUM(COMM_MGR_SUBMSG_TYPE) {
    ADD_ENUM(COMM_MGR_SUBMSG_DISCOVERY)
    ADD_ENUM(COMM_MGR_SUBMSG_LEARNING)
    ADD_ENUM(COMM_MGR_SUBMSG_DATATXREADY)
    ADD_ENUM(COMM_MGR_SUBMSG_PROTO_ACK)
    ADD_ENUM(COMM_MGR_SUBMSG_PROTO_NACK)
    ADD_ENUM(COMM_MGR_SUBMSG_DATA_ACK)
    ADD_ENUM(COMM_MGR_SUBMSG_DATA_NACK)
    ADD_ENUM_STR(COMM_MGR_SUBMSG_ANC_LEARNING, "Used to learn about Ancillary Server FD")
    ADD_ENUM_STR(COMM_MGR_SUBMSG_ANC_NACK, "No Ancillary Channel present")
} END_ENUM(COMM_MGR_SUBMSG_TYPE);

BEGIN_ENUM(COMM_MGR_ANC_MSG_TYPE) {
    ADD_ENUM_STR(COMM_MGR_ANC_MSG_DATA, "User data")
    ADD_ENUM_STR(COMM_MGR_ANC_MSG_SYSTEM_INFO, "Used for system related info")
    ADD_ENUM_STR(COMM_MGR_ANC_MSG_INTERFACE, "Used for interfacing related messaging")
    ADD_ENUM(COMM_MGR_MSG_ANC_MSG_MAX)
} END_ENUM(COMM_MGR_ANC_MSG_TYPE);

// Learning sub message specific actions
BEGIN_ENUM(COMM_MGR_SUBMSG_LEARNING_ACTION_TYPE) {
    ADD_ENUM_STR(COMM_MGR_SUBMSG_LEARNING_ACTION_START, "Dest UID is learnt")
    ADD_ENUM_STR(COMM_MGR_SUBMSG_LEARNING_ACTION_STOP, "Stop sending to dest UID")
    ADD_ENUM_STR(COMM_MGR_SUBMSG_LEARNING_ACTION_ANC_STOP, "Stop sending Ancillary message to dest UID")
    ADD_ENUM_STR(COMM_MGR_SUBMSG_LEARNING_ACTION_ABORT, "Abort sending to ALL dest UID")
    ADD_ENUM_STR(COMM_MGR_SUBMSG_LEARNING_ACTION_RESTART, "Restart the Protocol stage again")
    ADD_ENUM_STR(COMM_MGR_SUBMSG_LEARNING_ACTION_THROTTLE, "Throttle messages to a dest UID")
    ADD_ENUM_STR(COMM_MGR_SUBMSG_LEARNING_ACTION_THROTTLE_ALL, "Throttle messages to ALL dest UID")
    ADD_ENUM(COMM_MGR_SUBMSG_LEARNING_ACTION_INVALID)
} END_ENUM(COMM_MGR_SUBMSG_LEARNING_ACTION_TYPE);

// Below are the Communication Manager msg priority in Order
BEGIN_ENUM(COMM_MGR_MSG_PRIORITY) {
    ADD_ENUM_VAL(COMM_MGR_MSG_PRIORITY_CRITICAL, 0xA)
    ADD_ENUM_VAL(COMM_MGR_MSG_PRIORITY_HIGH, 0xB)
    ADD_ENUM_VAL(COMM_MGR_MSG_PRIORITY_NORMAL, 0xC) // Default priority
    ADD_ENUM_VAL(COMM_MGR_MSG_PRIORITY_LOW, 0xD)
    ADD_ENUM_VAL(COMM_MGR_MSG_PRIORITY_DEBUG, 0xE)
} END_ENUM(COMM_MGR_MSG_PRIORITY);

#endif /* INCLUDE_COMM_MGR_CMN_ENUMS_H__ */ 
