/******************************************************************************
  Note : This is a Auto Generated File. DO NOT EDIT THIS FILE !!!
  FileName : ./apps/shell/cli/test_comm_mgr_lib_cli.c
  Date : 2020-05-13 18:13:24
*******************************************************************************/

const char* test_comm_mgr_lib_cli[] = 
{
  "show test_comm_mgr_lib_cli uptime",
  "show test_comm_mgr_lib_cli option1",
  "show test_comm_mgr_lib_cli option2",

};
