/*******************************************************************************
    Description: Contains all the protypes for the system manager
    

*******************************************************************************/

#include "smarthome_essentials.h"

#define SYS_MGR_ERR_BASE        (SMARTHOME_ERROR_CODE_SYS_MGR)

BEGIN_ENUM(SYS_MGR_ERR) {
    ADD_ENUM_VAL(SYS_MGR_SUCCESS, 0)
    ADD_ENUM_VAL(SYS_MGR_INIT_FAILURE, SYS_MGR_ERR_BASE)
    ADD_ENUM(SYS_MGR_CLIENT_INIT_FAILURE)
} END_ENUM (SYS_MGR_ERR);


BEGIN_ENUM(SYS_MGR_CLIENT_BOOT_MODE) {
    ADD_ENUM_STR(SYS_MGR_CLIENT_BOOT_ONCE, "Boot only once")
    ADD_ENUM_STR(SYS_MGR_CLIENT_BOOT_ALWAYS, "Boot always upon process crash")
    ADD_ENUM_STR(SYS_MGR_CLIENT_BOOT_TRY, "Boot X number of times upon process crash")
} END_ENUM(SYS_MGR_CLIENT_BOOT_MODE);

BEGIN_ENUM(SYS_MGR_CLIENT_PRIORITY) {
    ADD_ENUM_VAL(SYS_MGR_CLIENT_PRIO_LOW, 0)
    ADD_ENUM(SYS_MGR_CLIENT_PRIO_NORMAL) // Most of the process starts with this priority
    ADD_ENUM(SYS_MGR_CLIENT_PRIO_HIGH)
    ADD_ENUM(SYS_MGR_CLIENT_PRIO_CRITICAL) // For critical apps, without which system can malform.
} END_ENUM(SYS_MGR_CLIENT_PRIORITY);

BEGIN_ENUM(SYS_MGR_CLIENT_HEAP_LIMIT) {
    ADD_ENUM(SYS_MGR_CLIENT_HEAP_500M)
    ADD_ENUM(SYS_MGR_CLIENT_HEAP_700M) // 700 MB
    ADD_ENUM(SYS_MGR_CLIENT_HEAP_1GB)
    ADD_ENUM(SYS_MGR_CLIENT_HEAP_2GB)
    ADD_ENUM(SYS_MGR_CLIENT_HEAP_2p5GB) // 2.5 GB
    ADD_ENUM(SYS_MGR_CLIENT_HEAP_USER_DEFINED)
} END_ENUM(SYS_MGR_CLIENT_HEAP_LIMIT);

BEGIN_ENUM(SYS_MGR_CLIENT_STATE) {
    ADD_ENUM(SYS_MGR_CLIENT_STATE_STOPPED)
    ADD_ENUM(SYS_MGR_CLIENT_STATE_RUNNING)
    ADD_ENUM(SYS_MGR_CLIENT_STATE_PAUSED)
} END_ENUM(SYS_MGR_CLIENT_STATE);


// Add the clients which needs to be managed by sys manager
BEGIN_ENUM(SYS_MGR_CLIENTS) {
    ADD_ENUM_VAL_STR(SYS_MGR_CLIENT_IPC_MANAGER, 0, "Communication Manager")
    ADD_ENUM_STR(SYS_MGR_CLIENT_APP_MANAGER, "Application Manager")
    ADD_ENUM_STR(SYS_MGR_CLIENT_DATABASE_MANAGER, "Database Manager")
    ADD_ENUM_STR(SYS_MGR_CLIENT_USERS_MANAGER, "Users Manager")
    ADD_ENUM(SYS_MGR_CLIENT_MAX_CLIENTS)
} END_ENUM(SYS_MGR_CLIENTS);


