/******************************************************************************
  Note : This is a Auto Generated File. DO NOT EDIT THIS FILE !!!
  FileName : ./apps/shell/shell_intf.h
  Date : 2020-05-21 13:05:30
*******************************************************************************/

#ifndef INCLUDE_SHELL_INTF_H__
#define INCLUDE_SHELL_INTF_H__


#include "test_comm_mgr_lib_cli.h"


SHELL_SUPPORTED_APP shell_supported_apps[] = {
	{
		 .appName = "test_comm_mgr_lib_cli",
		 .uid = 1023,
		 .uid_type = SHELL_APP_UID_STATIC,
		 .appArray = test_comm_mgr_lib_cli_query,
	},
	{
		 .appName = NULL
	},

};



#endif /*INCLUDE_SHELL_INTF_H__*/
